version: '3.8'

services:
  redis:
    image: redis:7
    container_name: node_boilerplate_redis
    ports:
      - '6379:6379'
    networks:
      - app-network

  app:
    build: .
    container_name: node_boilerplate_app
    ports:
      - '3000:3000'
    environment:
      REDIS_URL: redis://redis:6379
      FIREBASE_API_KEY: ${FIREBASE_API_KEY}
    depends_on:
      - redis
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

networks:
  app-network:
    driver: bridge

# Volumes removidos pois Postgres não é mais necessário
